apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vj3z
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eofv-tenant/rhtap-demo-app/hacbs-test-project-vj3z@sha256:e5750d69c8f7d0149490a9855364aa9ed2ede122b59a4245bd55b9ed89ca7746
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
